build: off
environment:

  matrix:
    - PLATFORMIO_PROJECT_DIR: "examples/arduino-blink"
    - PLATFORMIO_PROJECT_DIR: "examples/simba-blink"
    - PLATFORMIO_PROJECT_DIR: "examples/native-blink"


install:
  - cmd: git submodule update --init --recursive
  - cmd: SET PATH=C:\Python37\Scripts;%PATH%
  - cmd: pip3 install -U https://github.com/OS-Q/S03/archive/master.zip
  - cmd: qio platform install file://.

test_script:
- cmd: qio run -d %PLATFORMIO_PROJECT_DIR%
