build: off
environment:

  matrix:
    - PLATFORMIO_PROJECT_DIR: "examples/arduino-blink"
    - PLATFORMIO_PROJECT_DIR: "examples/arduino-wifiscan"
    - PLATFORMIO_PROJECT_DIR: "examples/arduino-webserver"
    - PLATFORMIO_PROJECT_DIR: "examples/simba-blink"

platform:
  - x64
install:
  - cmd: git submodule update --init --recursive
  - cmd: SET PATH=C:\Python37\Scripts;%PATH%
  - cmd: pip3 install -U https://github.com/OS-Q/M03/releases/latest/download/qio.zip
  - cmd: qio platform install file://.

test_script:
  - cmd: qio run -d %PLATFORMIO_PROJECT_DIR%
