version: 2
jobs:

  PIO:
    docker:
      - image: python:3
    steps:
      - checkout
      - run:
          name: "Install"
          command: |
            apt update
            apt install -y git
            git submodule update --init --recursive
            python -m pip install --upgrade pip
            pip install -U https://github.com/platformio/platformio/archive/develop.zip
            pio platform install https://github.com/OS-Q/P52/archive/pio.zip
      - run:
          name: "Build"
          command: |
            pio run -d examples/arduino-blink
            pio run -d examples/esp8266-nonos-sdk-blink
            pio run -d examples/esp8266-rtos-sdk-blink
            pio run -d examples/simba-blink

workflows:
    version: 2
    run_ci:
        jobs:
          - PIO
