name: CI

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '**.md'
      # - '**.yml'

env:
  UPLOAD_BUILD: true

jobs:
  CodeCheck:
    name: CodeCheck
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2
      with:
        submodules: "recursive"

    - name: cppcheck
      uses: Qful/check-action@master
      with:
        github_token: ${{ secrets.OSQ_REPO_TOKEN }}
        # check_library: disable
        # skip_preprocessor: disable
        # exclude_check: ./project/
        enable: all #performance,portability,warning
        inconclusive: disable
        inline_suppression: disable
        force_language: c
        force: enable
        max_ctu_depth: 2
        # platform: disable
        std: c11
        output_file: ./codecheck.txt
        other_options: --bug-hunting --verbose --std=c11

    - name: report
      uses: Qful/check-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.OSQ_REPO_TOKEN }}
        BRANCH_NAME: 'master'

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: code_check_report
        path: codecheck.txt

  PIO:
    strategy:
      fail-fast: false
      matrix:
        example:
          - "arduino"
          - "native"
          - "simba"

        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install PIO
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/platformio/platformio/archive/develop.zip
          pio platform install file://.

      - name: Build examples
        id: build
        if: success()
        working-directory: examples
        run: |
          pio run -d ${{ matrix.example }} >> ${{ matrix.example }}/log.txt
          echo "::set-output name=status::success"


      - name: Upload
        if: env.UPLOAD_BUILD
        uses: actions/upload-artifact@v2
        with:
          name: pio_${{ matrix.example }}
          path: examples/${{ matrix.example }}

  QIO:
    strategy:
      fail-fast: false
      matrix:
        example:
          - "arduino"
          - "native"
          - "simba"

        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install QIO
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/OS-Q/M03/releases/latest/download/qio.zip
          pio platform install file://.

      - name: Build examples
        id: build
        if: success()
        working-directory: examples
        run: |
          pio run -d ${{ matrix.example }} >> ${{ matrix.example }}/log.txt
          # cp -f ${{ matrix.example }}/.*io/build/**/*.bin  ${{ matrix.example }}/
          echo "::set-output name=status::success"

      - name: Upload
        if: env.UPLOAD_BUILD
        uses: actions/upload-artifact@v2
        with:
          name: qio_${{ matrix.example }}
          path: examples/${{ matrix.example }}/

  build_ok:
    needs:
      - QIO
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: notification
        uses: Qful/mqtt-action@master
        with:
          protocol: mqtt
          host: ${{secrets.MQTT_SERVER}}
          port: 1883
          username: ${{secrets.MQTT_USERNAME}}
          password: ${{secrets.MQTT_PASSWORD}}
          topic: ${{github.repository}}/${{github.workflow}}
          message: "QIO success"

